In [1]:
import pandas as pd
import numpy as np

In [2]:
qs = pd.read_csv("2026_QS_World University_Rankings.csv")

In [3]:
the = pd.read_excel("THE World University Rankings 2026.xlsx")

In [5]:
qs.head()

,Rank,Previous Rank,Name,Country/Territory,Region,Size,Focus,Research,Status,Academic Reputation SCORE,...,International student RANK,International Students Diversity SCORE,International Students Diversity RANK,International Research Network SCORE,International Research Network RANK,Employment Outcomes SCORE,Employment Outcomes RANK,Sustainability SCORE,Sustainability RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153.0,92.3,130.0,94.1,98.0,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35.0,100.0,22.0,97.5,28.0,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261.0,76.1,230.0,96.5,49.0,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80.0,98.7,67.0,100.0,1.0,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217.0,60.6,335.0,99.4,8.0,100.0,1,77.8,201=,97.7

In [6]:
the.head()

,Rank,Name,Country,Student Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1,University of Oxford,United Kingdom,22005,10.4,0.43,1900-01-02 04:48:00,98.2100,97.2,100.0,97.7,99.9,96.4,2026
1,2,Massachusetts Institute of Technology,United States,11703,7.7,0.33,1900-01-01 19:57:00,97.6735,99.2,95.3,99.6,100.0,91.9,2026
2,3,Princeton University,United States,8739,8.2,0.23,1900-01-01 23:53:00,97.2110,98.2,97.3,99.0,98.0,85.4,2026
3,4,University of Cambridge,United Kingdom,21045,11.3,0.38,1900-01-02 02:50:00,97.2065,96.2,99.9,97.1,87.6,96.3,2026
4,5,Stanford University,United States,17422,5.9,0.25,1900-01-02 00:52:00,97.1510,97.5,97.4,99.5,100.0,83.9,2026

In [7]:
qs.shape

(1504, 30)

In [8]:
the.shape

(2191, 14)

In [9]:
qs.columns

Index(['Rank', 'Previous Rank', 'Name', 'Country/Territory', 'Region', 'Size',
       'Focus', 'Research', 'Status', 'Academic Reputation SCORE',
       'Academic Reputation  RANK', 'Employer Reputation SCORE',
       'Employer Reputation RANK', 'Faculty Student Ratio SCORE',
       'Faculty Student Ratio RANK', 'Citations per Faculty SCORE',
       'Citations per Faculty RANK', 'International Faculty  SCORE',
       'International Faculty  RANK', 'International Student SCORE',
       'International student  RANK', 'International Students Diversity SCORE',
       'International Students Diversity RANK',
       'International Research Network SCORE',
       'International Research Network RANK', 'Employment Outcomes SCORE',
       'Employment Outcomes RANK', 'Sustainability SCORE',
       'Sustainability RANK', 'Overall SCORE'],
      dtype='object')

In [10]:
the.columns

Index(['Rank', 'Name', 'Country', 'Student Population',
       'Students to Staff Ratio', 'International Students',
       'Female to Male Ratio', 'Overall Score', 'Teaching',
       'Research Environment', 'Research Quality', 'Industry Impact',
       'International Outlook', 'Year'],
      dtype='object')

In [15]:
df= pd.concat([qs, the], ignore_index=True)

In [16]:
df.head()

,Rank,Previous Rank,Name,Country/Territory,Region,Size,Focus,Research,Status,Academic Reputation SCORE,...,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df

,Rank,Previous Rank,Name,Country/Territory,Region,Size,Focus,Research,Status,Academic Reputation SCORE,...,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3690,2187,NaN,Instituto TecnolÃ³gico Metropolitano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.7,0.00,1900-01-01 19:57:00,11.8620,12.9,7.9,9.0,18.7,30.9,2026.0
3691,2188,NaN,Universidad Pedagogica y Tecnologica de Colomb...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.7,0.00,1900-01-02 07:45:00,11.4340,13.9,8.0,6.0,16.4,34.1,2026.0
3692,2189,NaN,Omsk State Technical University,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.6,0.08,34 : 66,11.1660,15.6,8.2,5.0,19.9,25.2,2026.0
3693,2190,NaN,"Federal Institute of Education, Science and Te...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,0.00,37 : 63,10.8635,12.6,7.1,8.8,17.5,23.3,2026.0
3694,2191,NaN,Tula State University,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.5,0.06,39 : 61,10.2740,14.0,8.4,4.4,17.7,22.4,2026.0

In [25]:
  qs.columns

Index(['Rank', 'Previous Rank', 'Name', 'Country/Territory', 'Region', 'Size',
       'Focus', 'Research', 'Status', 'Academic Reputation SCORE',
       'Academic Reputation  RANK', 'Employer Reputation SCORE',
       'Employer Reputation RANK', 'Faculty Student Ratio SCORE',
       'Faculty Student Ratio RANK', 'Citations per Faculty SCORE',
       'Citations per Faculty RANK', 'International Faculty  SCORE',
       'International Faculty  RANK', 'International Student SCORE',
       'International student  RANK', 'International Students Diversity SCORE',
       'International Students Diversity RANK',
       'International Research Network SCORE',
       'International Research Network RANK', 'Employment Outcomes SCORE',
       'Employment Outcomes RANK', 'Sustainability SCORE',
       'Sustainability RANK', 'Overall SCORE'],
      dtype='object')

In [26]:
the.columns

Index(['Rank', 'Name', 'Country', 'Student Population',
       'Students to Staff Ratio', 'International Students',
       'Female to Male Ratio', 'Overall Score', 'Teaching',
       'Research Environment', 'Research Quality', 'Industry Impact',
       'International Outlook', 'Year'],
      dtype='object')

In [66]:
the = the.rename(columns={
    'Name': 'University Name',
    'Student Population': 'Academic Reputation Score',
    'Students to Staff Ratio': 'Faculty Student Ratio SCORE',
    'International Students': 'International Student SCORE',
    'Female to Male Ratio': 'International Students Diversity SCORE',
    'Teaching': 'International Faculty  SCORE',
    'Research Environment': 'Research SCORE',
    'Research Quality' : 'International Research Network SCORE',
    'Industry Impact': 'Employment Outcomes SCORE',
    'International Outlook': 'Employer Reputation SCORE',
    })

In [59]:
qs = qs.rename(columns={
    'Name': 'University Name',
    'Citations per Faculty SCORE': 'Research SCORE',
    })

In [60]:
df2 = pd.concat([qs, the], ignore_index=True)

In [62]:
df2.shape

(3695, 39)

In [63]:
df2.columns.tolist()

['Rank',
 'University Name',
 'Country',
 'Size',
 'Focus',
 'Research',
 'Status',
 'Academic Reputation SCORE',
 'Academic Reputation  RANK',
 'Employer Reputation SCORE',
 'Employer Reputation RANK',
 'Faculty Student Ratio SCORE',
 'Faculty Student Ratio RANK',
 'Research Score',
 'Citations per Faculty RANK',
 'International Faculty  SCORE',
 'International Faculty  RANK',
 'International Student SCORE',
 'International student  RANK',
 'International Students Diversity SCORE',
 'International Students Diversity RANK',
 'International Research Network SCORE',
 'International Research Network RANK',
 'Employment Outcomes SCORE',
 'Employment Outcomes RANK',
 'Sustainability SCORE',
 'Sustainability RANK',
 'Overall SCORE',
 'Academic Reputation Score',
 'Faculty Student Ratio Score',
 'International Student Score',
 'International Student Diversity Score',
 'Overall Score',
 'International Faculty Score',
 'Research score',
 'International Research Network Score',
 'Employment Outcomes Score',
 'Employer Reputation Score',
 'Year']

In [67]:
df2.columns.tolist()

['Rank',
 'University Name',
 'Country',
 'Size',
 'Focus',
 'Research',
 'Status',
 'Academic Reputation SCORE',
 'Academic Reputation  RANK',
 'Employer Reputation SCORE',
 'Employer Reputation RANK',
 'Faculty Student Ratio SCORE',
 'Faculty Student Ratio RANK',
 'Research Score',
 'Citations per Faculty RANK',
 'International Faculty  SCORE',
 'International Faculty  RANK',
 'International Student SCORE',
 'International student  RANK',
 'International Students Diversity SCORE',
 'International Students Diversity RANK',
 'International Research Network SCORE',
 'International Research Network RANK',
 'Employment Outcomes SCORE',
 'Employment Outcomes RANK',
 'Sustainability SCORE',
 'Sustainability RANK',
 'Overall SCORE',
 'Academic Reputation Score',
 'Faculty Student Ratio Score',
 'International Student Score',
 'International Student Diversity Score',
 'Overall Score',
 'International Faculty Score',
 'Research score',
 'International Research Network Score',
 'Employment Outcomes Score',
 'Employer Reputation Score',
 'Year']

In [70]:
the = the.rename(columns={
 'Academic Reputation Score': 'Academic Reputation SCORE',
 'Faculty Student Ratio Score': 'Faculty Student Ratio SCORE',
 'International Student Score': 'International Student SCORE',
 'International Student Diversity Score': 'International Students Diversity SCORE',
 'Overall Score': 'Overall SCORE',
 'International Faculty Score': 'International Faculty  SCORE',
 'International Research Network Score': 'International Research Network SCORE',
 'Employment Outcomes Score': 'Employment Outcomes SCORE',
 'Employer Reputation Score': 'Employer Reputation SCORE',
})

In [71]:
df3 = pd.concat([qs, the], ignore_index=True)

In [72]:
df3.shape

(3695, 30)

In [73]:
df3.columns.tolist()

['Rank',
 'University Name',
 'Country',
 'Size',
 'Focus',
 'Research',
 'Status',
 'Academic Reputation SCORE',
 'Academic Reputation  RANK',
 'Employer Reputation SCORE',
 'Employer Reputation RANK',
 'Faculty Student Ratio SCORE',
 'Faculty Student Ratio RANK',
 'Research Score',
 'Citations per Faculty RANK',
 'International Faculty  SCORE',
 'International Faculty  RANK',
 'International Student SCORE',
 'International student  RANK',
 'International Students Diversity SCORE',
 'International Students Diversity RANK',
 'International Research Network SCORE',
 'International Research Network RANK',
 'Employment Outcomes SCORE',
 'Employment Outcomes RANK',
 'Sustainability SCORE',
 'Sustainability RANK',
 'Overall SCORE',
 'Research score',
 'Year']

In [74]:
the = the.rename(columns={
 'Research score':  'Research Score',
})

In [75]:
df4 = pd.concat([qs, the], ignore_index=True)

In [77]:
df4.shape

(3695, 29)

In [79]:
df4.to_excel("data_collection.py.xlsx", index=False)

In [7]:
import pandas as pd

df4 = pd.read_excel("data_collection.py.xlsx")

In [8]:
df4.shape

(3695, 29)

In [9]:
clean_df4 = df4.copy()

In [10]:
clean_df4.columns

Index(['Rank', 'University Name', 'Country', 'Size', 'Focus', 'Research',
       'Status', 'Academic Reputation SCORE', 'Academic Reputation  RANK',
       'Employer Reputation SCORE', 'Employer Reputation RANK',
       'Faculty Student Ratio SCORE', 'Faculty Student Ratio RANK',
       'Research Score', 'Citations per Faculty RANK',
       'International Faculty  SCORE', 'International Faculty  RANK',
       'International Student SCORE', 'International student  RANK',
       'International Students Diversity SCORE',
       'International Students Diversity RANK',
       'International Research Network SCORE',
       'International Research Network RANK', 'Employment Outcomes SCORE',
       'Employment Outcomes RANK', 'Sustainability SCORE',
       'Sustainability RANK', 'Overall SCORE', 'Year'],
      dtype='object')

In [11]:
clean_df4.head()

,Rank,University Name,Country,Size,Focus,Research,Status,Academic Reputation SCORE,Academic Reputation RANK,Employer Reputation SCORE,...,International Students Diversity SCORE,International Students Diversity RANK,International Research Network SCORE,International Research Network RANK,Employment Outcomes SCORE,Employment Outcomes RANK,Sustainability SCORE,Sustainability RANK,Overall SCORE,Year
0,1,Massachusetts Institute of Technology (MIT),United States of America,M,CO,VH,Private not for Profit,100.0,4.0,100.0,...,92.3,130.0,94.1,98.0,100.0,7.0,93.8,33,100,NaN
1,2,Imperial College London,United Kingdom,L,FO,VH,Public,99.6,22.0,100.0,...,100,22.0,97.5,28.0,95.9,68.0,98.3,7=,99.4,NaN
2,3,Stanford University,United States of America,L,FC,VH,Private not for Profit,100.0,5.0,100.0,...,76.1,230.0,96.5,49.0,100.0,2.0,95.4,19=,98.9,NaN
3,4,University of Oxford,United Kingdom,L,FC,VH,Public,100.0,2.0,100.0,...,98.7,67.0,100.0,1.0,100.0,3.0,77.9,198=,97.9,NaN
4,5,Harvard University,United States of America,L,FC,VH,Private not for Profit,100.0,1.0,100.0,...,60.6,335.0,99.4,8.0,100.0,1.0,77.8,201=,97.7,NaN

In [12]:
clean_df4.isnull().sum()

Rank                                         0
University Name                              0
Country                                      0
Size                                      2192
Focus                                     2191
Research                                  2192
Status                                    2239
Academic Reputation SCORE                    0
Academic Reputation  RANK                 2191
Employer Reputation SCORE                    0
Employer Reputation RANK                  2191
Faculty Student Ratio SCORE                  0
Faculty Student Ratio RANK                2191
Research Score                               0
Citations per Faculty RANK                2191
International Faculty  SCORE                87
International Faculty  RANK               2278
International Student SCORE                 39
International student  RANK               2228
International Students Diversity SCORE     125
International Students Diversity RANK     2228
International Research Network SCORE         2
International Research Network RANK       2193
Employment Outcomes SCORE                    0
Employment Outcomes RANK                  2191
Sustainability SCORE                      2215
Sustainability RANK                       2215
Overall SCORE                                0
Year                                      1504
dtype: int64

In [13]:
(clean_df4.isnull().sum() / len(clean_df4) * 100).sort_values(ascending=False)

International Faculty  RANK               61.650880
Status                                    60.595399
International Students Diversity RANK     60.297700
International student  RANK               60.297700
Sustainability RANK                       59.945873
Sustainability SCORE                      59.945873
International Research Network RANK       59.350474
Size                                      59.323410
Research                                  59.323410
Citations per Faculty RANK                59.296346
Focus                                     59.296346
Academic Reputation  RANK                 59.296346
Employment Outcomes RANK                  59.296346
Employer Reputation RANK                  59.296346
Faculty Student Ratio RANK                59.296346
Year                                      40.703654
International Students Diversity SCORE     3.382950
International Faculty  SCORE               2.354533
International Student SCORE                1.055480
International Research Network SCORE       0.054127
University Name                            0.000000
Research Score                             0.000000
Faculty Student Ratio SCORE                0.000000
Employment Outcomes SCORE                  0.000000
Employer Reputation SCORE                  0.000000
Academic Reputation SCORE                  0.000000
Country                                    0.000000
Overall SCORE                              0.000000
Rank                                       0.000000
dtype: float64

In [15]:
clean_df4.duplicated().sum()

0

In [16]:
clean_df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3695 entries, 0 to 3694
Data columns (total 29 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Rank                                    3695 non-null   object
 1   University Name                         3695 non-null   object
 2   Country                                 3695 non-null   object
 3   Size                                    1503 non-null   object
 4   Focus                                   1504 non-null   object
 5   Research                                1503 non-null   object
 6   Status                                  1456 non-null   object
 7   Academic Reputation SCORE               3695 non-null   float64
 8   Academic Reputation  RANK               1504 non-null   float64
 9   Employer Reputation SCORE               3695 non-null   float64
 10  Employer Reputation RANK                1504 non-null   float64
 11  Faculty Student Ratio SCORE             3695 non-null   float64
 12  Faculty Student Ratio RANK              1504 non-null   float64
 13  Research Score                          3695 non-null   float64
 14  Citations per Faculty RANK              1504 non-null   float64
 15  International Faculty  SCORE            3608 non-null   float64
 16  International Faculty  RANK             1417 non-null   object
 17  International Student SCORE             3656 non-null   float64
 18  International student  RANK             1467 non-null   float64
 19  International Students Diversity SCORE  3570 non-null   object
 20  International Students Diversity RANK   1467 non-null   float64
 21  International Research Network SCORE    3693 non-null   float64
 22  International Research Network RANK     1502 non-null   float64
 23  Employment Outcomes SCORE               3695 non-null   float64
 24  Employment Outcomes RANK                1504 non-null   float64
 25  Sustainability SCORE                    1480 non-null   float64
 26  Sustainability RANK                     1480 non-null   object
 27  Overall SCORE                           3695 non-null   object
 28  Year                                    2191 non-null   float64
dtypes: float64(18), object(11)
memory usage: 837.3+ KB

In [18]:
clean_df4.describe()

,Academic Reputation SCORE,Academic Reputation RANK,Employer Reputation SCORE,Employer Reputation RANK,Faculty Student Ratio SCORE,Faculty Student Ratio RANK,Research Score,Citations per Faculty RANK,International Faculty SCORE,International Student SCORE,International student RANK,International Students Diversity RANK,International Research Network SCORE,International Research Network RANK,Employment Outcomes SCORE,Employment Outcomes RANK,Sustainability SCORE,Year
count,3695.000000,1504.000000,3695.000000,1504.000000,3695.000000,1504.000000,3695.000000,1504.000000,3608.000000,3656.000000,1467.000000,1467.000000,3693.000000,1502.000000,3695.000000,1504.000000,1480.000000,2191.0
mean,12817.500162,537.868351,40.311908,537.893617,24.560839,588.324468,25.926576,587.119681,31.820094,13.443561,582.668712,582.769598,52.656323,587.480027,40.699269,589.845080,51.230068,2026.0
std,21479.667436,222.718491,25.561173,222.734851,21.392693,262.003171,22.837453,261.814708,24.730875,26.379205,262.935739,262.981019,26.238627,261.509398,28.785896,261.614483,21.255581,0.0
min,1.000000,1.000000,1.000000,1.000000,0.700000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,2026.0
25%,21.350000,376.750000,20.900000,376.750000,11.950000,375.750000,10.500000,374.750000,16.100000,0.050000,366.500000,366.500000,30.100000,376.250000,17.950000,379.750000,35.700000,2026.0
50%,6488.000000,701.000000,36.100000,701.000000,17.400000,759.500000,17.500000,750.500000,25.100000,0.220000,738.000000,738.000000,53.900000,751.500000,32.600000,762.500000,48.700000,2026.0
75%,18825.500000,701.000000,56.400000,701.000000,27.700000,801.000000,34.300000,801.000000,38.500000,10.600000,801.000000,801.000000,74.800000,801.000000,63.450000,801.000000,66.425000,2026.0
max,499671.000000,701.000000,100.000000,701.000000,226.100000,801.000000,100.000000,801.000000,100.000000,100.000000,801.000000,801.000000,100.000000,801.000000,100.000000,801.000000,100.000000,2026.0

In [19]:
clean_df4.columns = clean_df4.columns.str.strip()

In [21]:
clean_df4.isnull().sum()

Rank                                         0
University Name                              0
Country                                      0
Size                                      2192
Focus                                     2191
Research                                  2192
Status                                    2239
Academic Reputation SCORE                    0
Academic Reputation  RANK                 2191
Employer Reputation SCORE                    0
Employer Reputation RANK                  2191
Faculty Student Ratio SCORE                  0
Faculty Student Ratio RANK                2191
Research Score                               0
Citations per Faculty RANK                2191
International Faculty  SCORE                87
International Faculty  RANK               2278
International Student SCORE                 39
International student  RANK               2228
International Students Diversity SCORE     125
International Students Diversity RANK     2228
International Research Network SCORE         2
International Research Network RANK       2193
Employment Outcomes SCORE                    0
Employment Outcomes RANK                  2191
Sustainability SCORE                      2215
Sustainability RANK                       2215
Overall SCORE                                0
Year                                      1504
dtype: int64

In [22]:
clean_df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3695 entries, 0 to 3694
Data columns (total 29 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Rank                                    3695 non-null   object
 1   University Name                         3695 non-null   object
 2   Country                                 3695 non-null   object
 3   Size                                    1503 non-null   object
 4   Focus                                   1504 non-null   object
 5   Research                                1503 non-null   object
 6   Status                                  1456 non-null   object
 7   Academic Reputation SCORE               3695 non-null   float64
 8   Academic Reputation  RANK               1504 non-null   float64
 9   Employer Reputation SCORE               3695 non-null   float64
 10  Employer Reputation RANK                1504 non-null   float64
 11  Faculty Student Ratio SCORE             3695 non-null   float64
 12  Faculty Student Ratio RANK              1504 non-null   float64
 13  Research Score                          3695 non-null   float64
 14  Citations per Faculty RANK              1504 non-null   float64
 15  International Faculty  SCORE            3608 non-null   float64
 16  International Faculty  RANK             1417 non-null   object
 17  International Student SCORE             3656 non-null   float64
 18  International student  RANK             1467 non-null   float64
 19  International Students Diversity SCORE  3570 non-null   object
 20  International Students Diversity RANK   1467 non-null   float64
 21  International Research Network SCORE    3693 non-null   float64
 22  International Research Network RANK     1502 non-null   float64
 23  Employment Outcomes SCORE               3695 non-null   float64
 24  Employment Outcomes RANK                1504 non-null   float64
 25  Sustainability SCORE                    1480 non-null   float64
 26  Sustainability RANK                     1480 non-null   object
 27  Overall SCORE                           3695 non-null   object
 28  Year                                    2191 non-null   float64
dtypes: float64(18), object(11)
memory usage: 837.3+ KB

In [24]:
# Make a copy
clean_df4 = df4.copy()

# Fill text/category columns
text_cols = clean_df4.select_dtypes(include="object").columns

for col in text_cols:
    clean_df4[col] = clean_df4[col].fillna("Not Available")

# Fill numeric columns with their median
numeric_cols = clean_df4.select_dtypes(include="number").columns

for col in numeric_cols:
    clean_df4[col] = clean_df4[col].fillna(clean_df4[col].median())

In [25]:
clean_df4.isnull().sum().sum()

0

In [27]:
clean_df4.to_excel("university_cleaned.xlsx", index=False)

In [6]:
import pandas as pd

clean_df4 = pd.read_excel("university_cleaned.xlsx")

In [7]:
clean_df4.head()

,Rank,University Name,Country,Size,Focus,Research,Status,Academic Reputation SCORE,Academic Reputation RANK,Employer Reputation SCORE,...,International Students Diversity SCORE,International Students Diversity RANK,International Research Network SCORE,International Research Network RANK,Employment Outcomes SCORE,Employment Outcomes RANK,Sustainability SCORE,Sustainability RANK,Overall SCORE,Year
0,1,Massachusetts Institute of Technology (MIT),United States of America,M,CO,VH,Private not for Profit,100.0,4,100.0,...,92.3,130,94.1,98.0,100.0,7.0,93.8,33,100,2026
1,2,Imperial College London,United Kingdom,L,FO,VH,Public,99.6,22,100.0,...,100,22,97.5,28.0,95.9,68.0,98.3,7=,99.4,2026
2,3,Stanford University,United States of America,L,FC,VH,Private not for Profit,100.0,5,100.0,...,76.1,230,96.5,49.0,100.0,2.0,95.4,19=,98.9,2026
3,4,University of Oxford,United Kingdom,L,FC,VH,Public,100.0,2,100.0,...,98.7,67,100.0,1.0,100.0,3.0,77.9,198=,97.9,2026
4,5,Harvard University,United States of America,L,FC,VH,Private not for Profit,100.0,1,100.0,...,60.6,335,99.4,8.0,100.0,1.0,77.8,201=,97.7,2026

In [8]:
transformed_df = clean_df4.copy()

In [9]:
transformed_df.head()

,Rank,University Name,Country,Size,Focus,Research,Status,Academic Reputation SCORE,Academic Reputation RANK,Employer Reputation SCORE,...,International Students Diversity SCORE,International Students Diversity RANK,International Research Network SCORE,International Research Network RANK,Employment Outcomes SCORE,Employment Outcomes RANK,Sustainability SCORE,Sustainability RANK,Overall SCORE,Year
0,1,Massachusetts Institute of Technology (MIT),United States of America,M,CO,VH,Private not for Profit,100.0,4,100.0,...,92.3,130,94.1,98.0,100.0,7.0,93.8,33,100,2026
1,2,Imperial College London,United Kingdom,L,FO,VH,Public,99.6,22,100.0,...,100,22,97.5,28.0,95.9,68.0,98.3,7=,99.4,2026
2,3,Stanford University,United States of America,L,FC,VH,Private not for Profit,100.0,5,100.0,...,76.1,230,96.5,49.0,100.0,2.0,95.4,19=,98.9,2026
3,4,University of Oxford,United Kingdom,L,FC,VH,Public,100.0,2,100.0,...,98.7,67,100.0,1.0,100.0,3.0,77.9,198=,97.9,2026
4,5,Harvard University,United States of America,L,FC,VH,Private not for Profit,100.0,1,100.0,...,60.6,335,99.4,8.0,100.0,1.0,77.8,201=,97.7,2026

In [10]:
transformed_df.dtypes

Rank                                       object
University Name                            object
Country                                    object
Size                                       object
Focus                                      object
Research                                   object
Status                                     object
Academic Reputation SCORE                 float64
Academic Reputation  RANK                   int64
Employer Reputation SCORE                 float64
Employer Reputation RANK                    int64
Faculty Student Ratio SCORE               float64
Faculty Student Ratio RANK                float64
Research Score                            float64
Citations per Faculty RANK                float64
International Faculty  SCORE              float64
International Faculty  RANK                object
International Student SCORE               float64
International student  RANK                 int64
International Students Diversity SCORE     object
International Students Diversity RANK       int64
International Research Network SCORE      float64
International Research Network RANK       float64
Employment Outcomes SCORE                 float64
Employment Outcomes RANK                  float64
Sustainability SCORE                      float64
Sustainability RANK                        object
Overall SCORE                              object
Year                                        int64
dtype: object

In [13]:
for col in transformed_df.columns:
    print(repr(col))

'Rank'
'University Name'
'Country'
'Size'
'Focus'
'Research'
'Status'
'Academic Reputation SCORE'
'Academic Reputation  RANK'
'Employer Reputation SCORE'
'Employer Reputation RANK'
'Faculty Student Ratio SCORE'
'Faculty Student Ratio RANK'
'Research Score'
'Citations per Faculty RANK'
'International Faculty  SCORE'
'International Faculty  RANK'
'International Student SCORE'
'International student  RANK'
'International Students Diversity SCORE'
'International Students Diversity RANK'
'International Research Network SCORE'
'International Research Network RANK'
'Employment Outcomes SCORE'
'Employment Outcomes RANK'
'Sustainability SCORE'
'Sustainability RANK'
'Overall SCORE'
'Year'

In [14]:
for col in transformed_df.columns:
    if col not in ["University Name", "Country", "Size", "Focus", "Research", "Status"]:
        transformed_df[col] = pd.to_numeric(
            transformed_df[col],
            errors="coerce"
        )

In [15]:
transformed_df.dtypes

Rank                                      float64
University Name                            object
Country                                    object
Size                                       object
Focus                                      object
Research                                   object
Status                                     object
Academic Reputation SCORE                 float64
Academic Reputation  RANK                   int64
Employer Reputation SCORE                 float64
Employer Reputation RANK                    int64
Faculty Student Ratio SCORE               float64
Faculty Student Ratio RANK                float64
Research Score                            float64
Citations per Faculty RANK                float64
International Faculty  SCORE              float64
International Faculty  RANK               float64
International Student SCORE               float64
International student  RANK                 int64
International Students Diversity SCORE    float64
International Students Diversity RANK       int64
International Research Network SCORE      float64
International Research Network RANK       float64
Employment Outcomes SCORE                 float64
Employment Outcomes RANK                  float64
Sustainability SCORE                      float64
Sustainability RANK                       float64
Overall SCORE                             float64
Year                                        int64
dtype: object

In [16]:
transformed_df["Overall SCORE"].describe()

count    2896.000000
mean       38.940880
std        17.057014
min        10.274000
25%        26.900000
50%        35.218250
75%        48.037250
max       100.000000
Name: Overall SCORE, dtype: float64

In [17]:
transformed_df["Performance_Category"] = pd.cut(
    transformed_df["Overall SCORE"],
    bins=[0, 40, 60, 80, 100],
    labels=["Low", "Average", "Good", "Excellent"],
    include_lowest=True
)

In [18]:
transformed_df[["Overall SCORE", "Performance_Category"]].head(10)

   Overall SCORE Performance_Category
0          100.0            Excellent
1           99.4            Excellent
2           98.9            Excellent
3           97.9            Excellent
4           97.7            Excellent
5           97.2            Excellent
6           96.7            Excellent
7           95.9            Excellent
8           95.8            Excellent
9           94.3            Excellent

In [19]:
transformed_df["Rank_Category"] = pd.cut(
    transformed_df["Rank"],
    bins=[0, 100, 300, 500, float("inf")],
    labels=["Top 100", "101-300", "301-500", "501+"],
    include_lowest=True
)

In [20]:
transformed_df[["Rank", "Rank_Category"]].head(10)

   Rank Rank_Category
0   1.0       Top 100
1   2.0       Top 100
2   3.0       Top 100
3   4.0       Top 100
4   5.0       Top 100
5   6.0       Top 100
6   7.0       Top 100
7   8.0       Top 100
8   9.0       Top 100
9  10.0       Top 100

In [21]:
text_cols = [
    "University Name",
    "Country",
    "Size",
    "Focus",
    "Research",
    "Status"
]

for col in text_cols:
    transformed_df[col] = transformed_df[col].astype(str).str.strip()

In [22]:
transformed_df[text_cols].head()

,University Name,Country,Size,Focus,Research,Status
0,Massachusetts Institute of Technology (MIT),United States of America,M,CO,VH,Private not for Profit
1,Imperial College London,United Kingdom,L,FO,VH,Public
2,Stanford University,United States of America,L,FC,VH,Private not for Profit
3,University of Oxford,United Kingdom,L,FC,VH,Public
4,Harvard University,United States of America,L,FC,VH,Private not for Profit

In [23]:
transformed_df.duplicated().sum()

0

In [24]:
transformed_df.isnull().sum()

Rank                                       704
University Name                              0
Country                                      0
Size                                         0
Focus                                        0
Research                                     0
Status                                       0
Academic Reputation SCORE                    0
Academic Reputation  RANK                    0
Employer Reputation SCORE                    0
Employer Reputation RANK                     0
Faculty Student Ratio SCORE                  0
Faculty Student Ratio RANK                   0
Research Score                               0
Citations per Faculty RANK                   0
International Faculty  SCORE                 0
International Faculty  RANK               2280
International Student SCORE                  0
International student  RANK                  0
International Students Diversity SCORE    2180
International Students Diversity RANK        0
International Research Network SCORE         0
International Research Network RANK          0
Employment Outcomes SCORE                    0
Employment Outcomes RANK                     0
Sustainability SCORE                         0
Sustainability RANK                       2869
Overall SCORE                              799
Year                                         0
Performance_Category                       799
Rank_Category                              704
dtype: int64

In [25]:
transformed_df["Performance_Category"] = (
    transformed_df["Performance_Category"]
    .astype("object")
    .fillna("Not Available")
)

transformed_df["Rank_Category"] = (
    transformed_df["Rank_Category"]
    .astype("object")
    .fillna("Not Available")
)

In [26]:
transformed_df[
    ["Overall SCORE", "Performance_Category", "Rank", "Rank_Category"]
].head(10)

   Overall SCORE Performance_Category  Rank Rank_Category
0          100.0            Excellent   1.0       Top 100
1           99.4            Excellent   2.0       Top 100
2           98.9            Excellent   3.0       Top 100
3           97.9            Excellent   4.0       Top 100
4           97.7            Excellent   5.0       Top 100
5           97.2            Excellent   6.0       Top 100
6           96.7            Excellent   7.0       Top 100
7           95.9            Excellent   8.0       Top 100
8           95.8            Excellent   9.0       Top 100
9           94.3            Excellent  10.0       Top 100

In [27]:
country_summary = (
    transformed_df
    .groupby("Country")
    .agg(
        University_Count=("University Name", "count"),
        Average_Overall_Score=("Overall SCORE", "mean")
    )
    .reset_index()
)

In [28]:
country_summary.head(10)

      Country  University_Count  Average_Overall_Score
0     Algeria                28              18.969464
1   Argentina                27              26.336115
2     Armenia                 2              17.864000
3   Australia                73              55.295860
4     Austria                21              45.950167
5  Azerbaijan                13              23.852300
6     Bahrain                 5              35.836000
7  Bangladesh                34              32.094725
8     Belarus                 4              27.555250
9     Belgium                20              54.139639

In [29]:
transformed_df.to_excel(
    "university_transformed.xlsx",
    index=False
)

In [30]:
country_summary.to_excel(
    "country_summary.xlsx",
    index=False
)

In [30]:
country_summary.to_excel(
    "country_summary.xlsx",
    index=False
)

In [31]:
transformed_df.shape

(3695, 31)

In [32]:
transformed_df.head()

,Rank,University Name,Country,Size,Focus,Research,Status,Academic Reputation SCORE,Academic Reputation RANK,Employer Reputation SCORE,...,International Research Network SCORE,International Research Network RANK,Employment Outcomes SCORE,Employment Outcomes RANK,Sustainability SCORE,Sustainability RANK,Overall SCORE,Year,Performance_Category,Rank_Category
0,1.0,Massachusetts Institute of Technology (MIT),United States of America,M,CO,VH,Private not for Profit,100.0,4,100.0,...,94.1,98.0,100.0,7.0,93.8,33.0,100.0,2026,Excellent,Top 100
1,2.0,Imperial College London,United Kingdom,L,FO,VH,Public,99.6,22,100.0,...,97.5,28.0,95.9,68.0,98.3,NaN,99.4,2026,Excellent,Top 100
2,3.0,Stanford University,United States of America,L,FC,VH,Private not for Profit,100.0,5,100.0,...,96.5,49.0,100.0,2.0,95.4,NaN,98.9,2026,Excellent,Top 100
3,4.0,University of Oxford,United Kingdom,L,FC,VH,Public,100.0,2,100.0,...,100.0,1.0,100.0,3.0,77.9,NaN,97.9,2026,Excellent,Top 100
4,5.0,Harvard University,United States of America,L,FC,VH,Private not for Profit,100.0,1,100.0,...,99.4,8.0,100.0,1.0,77.8,NaN,97.7,2026,Excellent,Top 100

In [43]:
country_summary.to_excel(
    "country_summary.xlsx",
    index=False
)

In [44]:
numeric_cols = transformed_df.select_dtypes(include="number").columns

for col in numeric_cols:
    transformed_df[col] = transformed_df[col].fillna(
        transformed_df[col].median()
    )

In [45]:
transformed_df.to_excel(
    "education_cleaning.ipynb.xlsx",
    index=False
)

In [46]:
print(transformed_df.columns.tolist())

['Rank', 'University Name', 'Country', 'Size', 'Focus', 'Research', 'Status', 'Academic Reputation SCORE', 'Academic Reputation  RANK', 'Employer Reputation SCORE', 'Employer Reputation RANK', 'Faculty Student Ratio SCORE', 'Faculty Student Ratio RANK', 'Research Score', 'Citations per Faculty RANK', 'International Faculty  SCORE', 'International Faculty  RANK', 'International Student SCORE', 'International student  RANK', 'International Students Diversity SCORE', 'International Students Diversity RANK', 'International Research Network SCORE', 'International Research Network RANK', 'Employment Outcomes SCORE', 'Employment Outcomes RANK', 'Sustainability SCORE', 'Sustainability RANK', 'Overall SCORE', 'Year', 'Rank_Numeric']

In [ ]:
transformed_df("")