# Education Data Cleaning & Transformation

## QS World University Rankings 2026 + THE World University Rankings 2026

### Internship Milestone 1 — Data Collection and Preparation

This notebook documents the cleaning, transformation, integration, and validation of the QS World University Rankings 2026 and Times Higher Education (THE) World University Rankings 2026 datasets.

### Objectives

- Load the QS and THE university ranking datasets
- Inspect and understand the datasets
- Clean text and encoding issues
- Standardize university names
- Standardize country names
- Normalize ranking and performance metrics
- Handle missing values appropriately
- Remove and validate duplicates
- Integrate QS and THE datasets
- Validate the merged dataset
- Measure data completeness
- Produce a Tableau-ready dataset

### Final Dataset

- Records: 1,008 universities
- Core completeness: 99.43%
- Missing core values: 0.57%
- Duplicate QS universities: 0
- Duplicate THE universities: 0
- Country mismatches: 0

**Milestone 1 Data Quality Requirement:**  
Completeness > 95% and missing values < 2%.

**Status: PASS**

# Education Data Cleaning & Transformation

## QS World University Rankings 2026 + THE World University Rankings 2026

### Internship Milestone 1 — Data Collection and Preparation

This notebook documents the cleaning, transformation, integration, and validation of the QS World University Rankings 2026 and Times Higher Education (THE) World University Rankings 2026 datasets.

### Objectives

- Load the QS and THE university ranking datasets
- Inspect and understand the datasets
- Clean text and encoding issues
- Standardize university names
- Standardize country names
- Normalize ranking and performance metrics
- Handle missing values appropriately
- Remove and validate duplicates
- Integrate QS and THE datasets
- Validate the merged dataset
- Measure data completeness
- Produce a Tableau-ready dataset

### Final Dataset

- Records: 1,008 universities
- Core completeness: 99.43%
- Missing core values: 0.57%
- Duplicate QS universities: 0
- Duplicate THE universities: 0
- Country mismatches: 0

**Milestone 1 Data Quality Requirement:**  
Completeness > 95% and missing values < 2%.

**Status: PASS**

In [2]:
import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# Project paths

BASE_DIR = Path.cwd().parent

DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "output"

print("Base directory:", BASE_DIR)
print("Data directory:", DATA_DIR)
print("Output directory:", OUTPUT_DIR)

Base directory: C:\Users\Asus\infosys internshi
Data directory: C:\Users\Asus\infosys internshi\data
Output directory: C:\Users\Asus\infosys internshi\output

In [4]:
# Load cleaned QS and THE datasets

QS_FILE = OUTPUT_DIR / "qs_cleaned_encoding_fixed.csv"
THE_FILE = OUTPUT_DIR / "the_cleaned_encoding_fixed.csv"

qs = pd.read_csv(QS_FILE, encoding="utf-8-sig")
the = pd.read_csv(THE_FILE, encoding="utf-8-sig")

print("QS dataset shape :", qs.shape)
print("THE dataset shape:", the.shape)

QS dataset shape : (1501, 36)
THE dataset shape: (2191, 18)

In [5]:
print("QS columns:")
display(pd.DataFrame({"Column": qs.columns}))

print("\nTHE columns:")
display(pd.DataFrame({"Column": the.columns}))

QS columns:

                     Column
0                 2026 Rank
1             Previous Rank
2          Institution Name
3         Country/Territory
4                    Region
5                      Size
6                     Focus
7                  Research
8                    Status
9                  AR SCORE
10                  AR RANK
11                 ER SCORE
12                  ER RANK
13                FSR SCORE
14                 FSR RANK
15                CPF SCORE
16                 CPF RANK
17                IFR SCORE
18                 IFR RANK
19                ISR SCORE
20                 ISR RANK
21                ISD SCORE
22                 ISD RANK
23                IRN SCORE
24                 IRN RANK
25                 EO SCORE
26                  EO RANK
27                SUS SCORE
28                 SUS RANK
29            Overall SCORE
30       2026_rank_original
31                2026_rank
32        2026_rank_display
33            overall_score
34  overall_score_available
35           university_key

THE columns:

                           Column
0                            Rank
1                            Name
2                         Country
3              Student Population
4         Students to Staff Ratio
5          International Students
6            Female to Male Ratio
7                   Overall Score
8                        Teaching
9            Research Environment
10               Research Quality
11                Industry Impact
12          International Outlook
13                           Year
14                           rank
15     female_to_male_ratio_clean
16  female_to_male_ratio_original
17                 university_key

In [6]:
print("QS Dataset Information")
display(qs.info())

print("\nTHE Dataset Information")
display(the.info())

QS Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 1501 entries, 0 to 1500
Data columns (total 36 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   2026 Rank                1501 non-null   str
 1   Previous Rank            595 non-null    float64
 2   Institution Name         1501 non-null   str
 3   Country/Territory        1501 non-null   str
 4   Region                   1501 non-null   str
 5   Size                     1500 non-null   str
 6   Focus                    1501 non-null   str
 7   Research                 1500 non-null   str
 8   Status                   1454 non-null   str
 9   AR SCORE                 1501 non-null   float64
 10  AR RANK                  700 non-null    float64
 11  ER SCORE                 1501 non-null   float64
 12  ER RANK                  699 non-null    float64
 13  FSR SCORE                1501 non-null   float64
 14  FSR RANK                 785 non-null    float64
 15  CPF SCORE                1501 non-null   float64
 16  CPF RANK                 800 non-null    float64
 17  IFR SCORE                1414 non-null   float64
 18  IFR RANK                 791 non-null    float64
 19  ISR SCORE                1464 non-null   float64
 20  ISR RANK                 795 non-null    float64
 21  ISD SCORE                1464 non-null   float64
 22  ISD RANK                 795 non-null    float64
 23  IRN SCORE                1499 non-null   float64
 24  IRN RANK                 799 non-null    float64
 25  EO SCORE                 1501 non-null   float64
 26  EO RANK                  788 non-null    float64
 27  SUS SCORE                1477 non-null   float64
 28  SUS RANK                 149 non-null    float64
 29  Overall SCORE            1501 non-null   str
 30  2026_rank_original       1501 non-null   str
 31  2026_rank                1501 non-null   float64
 32  2026_rank_display        1501 non-null   str
 33  overall_score            703 non-null    float64
 34  overall_score_available  1501 non-null   bool
 35  university_key           1501 non-null   str
dtypes: bool(1), float64(23), str(12)
memory usage: 412.0 KB

None

THE Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 2191 entries, 0 to 2190
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Rank                           2191 non-null   int64
 1   Name                           2191 non-null   str
 2   Country                        2191 non-null   str
 3   Student Population             2191 non-null   float64
 4   Students to Staff Ratio        2191 non-null   float64
 5   International Students         2189 non-null   float64
 6   Female to Male Ratio           2103 non-null   str
 7   Overall Score                  2191 non-null   float64
 8   Teaching                       2191 non-null   float64
 9   Research Environment           2191 non-null   float64
 10  Research Quality               2191 non-null   float64
 11  Industry Impact                2191 non-null   float64
 12  International Outlook          2191 non-null   float64
 13  Year                           2191 non-null   int64
 14  rank                           2191 non-null   float64
 15  female_to_male_ratio_clean     2055 non-null   float64
 16  female_to_male_ratio_original  2103 non-null   str
 17  university_key                 2191 non-null   str
dtypes: float64(11), int64(2), str(5)
memory usage: 308.2 KB

None

In [7]:
print("QS Dataset Information")
qs.info()

print("\nTHE Dataset Information")
the.info()

QS Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 1501 entries, 0 to 1500
Data columns (total 36 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   2026 Rank                1501 non-null   str
 1   Previous Rank            595 non-null    float64
 2   Institution Name         1501 non-null   str
 3   Country/Territory        1501 non-null   str
 4   Region                   1501 non-null   str
 5   Size                     1500 non-null   str
 6   Focus                    1501 non-null   str
 7   Research                 1500 non-null   str
 8   Status                   1454 non-null   str
 9   AR SCORE                 1501 non-null   float64
 10  AR RANK                  700 non-null    float64
 11  ER SCORE                 1501 non-null   float64
 12  ER RANK                  699 non-null    float64
 13  FSR SCORE                1501 non-null   float64
 14  FSR RANK                 785 non-null    float64
 15  CPF SCORE                1501 non-null   float64
 16  CPF RANK                 800 non-null    float64
 17  IFR SCORE                1414 non-null   float64
 18  IFR RANK                 791 non-null    float64
 19  ISR SCORE                1464 non-null   float64
 20  ISR RANK                 795 non-null    float64
 21  ISD SCORE                1464 non-null   float64
 22  ISD RANK                 795 non-null    float64
 23  IRN SCORE                1499 non-null   float64
 24  IRN RANK                 799 non-null    float64
 25  EO SCORE                 1501 non-null   float64
 26  EO RANK                  788 non-null    float64
 27  SUS SCORE                1477 non-null   float64
 28  SUS RANK                 149 non-null    float64
 29  Overall SCORE            1501 non-null   str
 30  2026_rank_original       1501 non-null   str
 31  2026_rank                1501 non-null   float64
 32  2026_rank_display        1501 non-null   str
 33  overall_score            703 non-null    float64
 34  overall_score_available  1501 non-null   bool
 35  university_key           1501 non-null   str
dtypes: bool(1), float64(23), str(12)
memory usage: 412.0 KB

THE Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 2191 entries, 0 to 2190
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Rank                           2191 non-null   int64
 1   Name                           2191 non-null   str
 2   Country                        2191 non-null   str
 3   Student Population             2191 non-null   float64
 4   Students to Staff Ratio        2191 non-null   float64
 5   International Students         2189 non-null   float64
 6   Female to Male Ratio           2103 non-null   str
 7   Overall Score                  2191 non-null   float64
 8   Teaching                       2191 non-null   float64
 9   Research Environment           2191 non-null   float64
 10  Research Quality               2191 non-null   float64
 11  Industry Impact                2191 non-null   float64
 12  International Outlook          2191 non-null   float64
 13  Year                           2191 non-null   int64
 14  rank                           2191 non-null   float64
 15  female_to_male_ratio_clean     2055 non-null   float64
 16  female_to_male_ratio_original  2103 non-null   str
 17  university_key                 2191 non-null   str
dtypes: float64(11), int64(2), str(5)
memory usage: 308.2 KB

In [8]:
print("QS missing values:")
display(
    qs.isna().sum()
    .sort_values(ascending=False)
    .to_frame("Missing Values")
)

print("\nTHE missing values:")
display(
    the.isna().sum()
    .sort_values(ascending=False)
    .to_frame("Missing Values")
)

QS missing values:

                         Missing Values
SUS RANK                           1352
Previous Rank                       906
ER RANK                             802
AR RANK                             801
overall_score                       798
FSR RANK                            716
EO RANK                             713
IFR RANK                            710
ISD RANK                            706
ISR RANK                            706
IRN RANK                            702
CPF RANK                            701
IFR SCORE                            87
Status                               47
ISR SCORE                            37
ISD SCORE                            37
SUS SCORE                            24
IRN SCORE                             2
Size                                  1
Research                              1
Country/Territory                     0
Institution Name                      0
2026 Rank                             0
CPF SCORE                             0
Focus                                 0
Region                                0
AR SCORE                              0
ER SCORE                              0
FSR SCORE                             0
EO SCORE                              0
2026_rank_original                    0
Overall SCORE                         0
2026_rank                             0
2026_rank_display                     0
overall_score_available               0
university_key                        0

THE missing values:

                               Missing Values
female_to_male_ratio_clean                136
Female to Male Ratio                       88
female_to_male_ratio_original              88
International Students                      2
Name                                        0
Rank                                        0
Students to Staff Ratio                     0
Overall Score                               0
Student Population                          0
Country                                     0
Research Environment                        0
Teaching                                    0
Research Quality                            0
Industry Impact                             0
Year                                        0
International Outlook                       0
rank                                        0
university_key                              0

In [9]:
def standardize_university_name(value):
    if pd.isna(value):
        return value

    value = str(value).strip()

    # Fix common encoding issues
    try:
        if any(x in value for x in ["Ã", "Â", "â", "Å", "Ä"]):
            value = value.encode("latin1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        pass

    # Unicode normalization
    value = unicodedata.normalize("NFKC", value)

    # Normalize whitespace
    value = re.sub(r"\s+", " ", value)

    return value.strip()


qs["Institution Name"] = qs["Institution Name"].apply(
    standardize_university_name
)

the["Name"] = the["Name"].apply(
    standardize_university_name
)

print("University names standardized successfully.")

University names standardized successfully.

In [10]:
def standardize_country_name(value):
    if pd.isna(value):
        return value

    value = str(value).strip()

    replacements = {
        "United States": "United States of America",
        "United States of America": "United States of America",
        "China": "China (Mainland)",
        "China (Mainland)": "China (Mainland)",
        "South Korea": "Republic of Korea",
        "Korea, Republic of": "Republic of Korea",
        "Republic of Korea": "Republic of Korea",
        "Russia": "Russian Federation",
        "Russian Federation": "Russian Federation",
        "Czech Republic": "Czechia",
        "Czechia": "Czechia",
    }

    return replacements.get(value, value)


qs["Country/Territory"] = qs["Country/Territory"].apply(
    standardize_country_name
)

the["Country"] = the["Country"].apply(
    standardize_country_name
)

print("Country names standardized successfully.")

Country names standardized successfully.

In [11]:
print("QS duplicate university names:",
      qs["Institution Name"].duplicated().sum())

print("THE duplicate university names:",
      the["Name"].duplicated().sum())

print("QS duplicate rows:",
      qs.duplicated().sum())

print("THE duplicate rows:",
      the.duplicated().sum())

QS duplicate university names: 0
THE duplicate university names: 0
QS duplicate rows: 0
THE duplicate rows: 0

In [12]:
FINAL_FILE = OUTPUT_DIR / "university_cleaned_merged_data.csv"

final_df = pd.read_csv(
    FINAL_FILE,
    encoding="utf-8-sig"
)

print("Final integrated dataset shape:", final_df.shape)

display(final_df.head())

Final integrated dataset shape: (1008, 61)

,qs_2026 Rank,qs_Previous Rank,qs_Institution Name,qs_Country/Territory,qs_Region,qs_Size,qs_Focus,qs_Research,qs_Status,qs_AR SCORE,qs_AR RANK,qs_ER SCORE,qs_ER RANK,qs_FSR SCORE,qs_FSR RANK,qs_CPF SCORE,qs_CPF RANK,qs_IFR SCORE,qs_IFR RANK,qs_ISR SCORE,qs_ISR RANK,qs_ISD SCORE,qs_ISD RANK,qs_IRN SCORE,qs_IRN RANK,qs_EO SCORE,qs_EO RANK,qs_SUS SCORE,qs_SUS RANK,qs_Overall SCORE,qs_2026_rank_original,qs_2026_rank,qs_2026_rank_display,qs_overall_score,qs_overall_score_available,qs_university_key,the_Rank,the_Name,the_Country,the_Student Population,the_Students to Staff Ratio,the_International Students,the_Female to Male Ratio,the_Overall Score,the_Teaching,the_Research Environment,the_Research Quality,the_Industry Impact,the_International Outlook,the_Year,the_rank,the_female_to_male_ratio_clean,the_female_to_male_ratio_original,the_university_key,match_type,match_similarity,country_match,qs_Institution Name_original,the_Name_original,qs_university_key_clean,the_university_key_clean
0,1.0,1.0,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,4.0,100.0,2.0,100.0,16.0,100.0,7.0,100.0,63.0,91.6,153.0,92.3,130.0,94.1,98.0,100.0,7.0,93.8,33.0,100,1,1.0,1,100.0,True,massachusetts institute of technology,2.0,Massachusetts Institute of Technology,United States of America,11703.0,7.7,0.33,"1 day, 19:57:00",97.6735,99.2,95.3,99.6,100.0,91.9,2026.0,2.0,43.0,"1 day, 19:57:00",massachusetts institute of technology,exact_name_country,100.0,True,Massachusetts Institute of Technology (MIT),Massachusetts Institute of Technology,massachusetts institute of technology,massachusetts institute of technology
1,2.0,2.0,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,22.0,100.0,9.0,99.3,42.0,95.0,69.0,100.0,74.0,100.0,35.0,100.0,22.0,97.5,28.0,95.9,68.0,98.3,NaN,99.4,2,2.0,2,99.4,True,imperial college london,8.0,Imperial College London,United Kingdom,21340.0,12.1,0.60,"1 day, 19:57:00",94.6890,90.6,94.9,98.0,91.9,98.2,2026.0,8.0,43.0,"1 day, 19:57:00",imperial college london,exact_name_country,100.0,True,Imperial College London,Imperial College London,imperial college london,imperial college london
2,3.0,6.0,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,5.0,100.0,3.0,100.0,17.0,99.7,24.0,94.2,188.0,73.5,261.0,76.1,230.0,96.5,49.0,100.0,2.0,95.4,NaN,98.9,3,3.0,3,98.9,True,stanford university,5.0,Stanford University,United States of America,17422.0,5.9,0.25,"2 days, 0:52:00",97.1510,97.5,97.4,99.5,100.0,83.9,2026.0,5.0,48.0,"2 days, 0:52:00",stanford university,exact_name_country,100.0,True,Stanford University,Stanford University,stanford university,stanford university
3,4.0,3.0,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,2.0,100.0,4.0,100.0,9.0,91.0,98.0,98.8,132.0,98.6,80.0,98.7,67.0,100.0,1.0,100.0,3.0,77.9,NaN,97.9,4,4.0,4,97.9,True,university of oxford,1.0,University of Oxford,United Kingdom,22005.0,10.4,0.43,"2 days, 4:48:00",98.2100,97.2,100.0,97.7,99.9,96.4,2026.0,1.0,52.0,"2 days, 4:48:00",university of oxford,exact_name_country,100.0,True,University of Oxford,University of Oxford,university of oxford,university of oxford
4,5.0,4.0,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,1.0,100.0,1.0,98.3,50.0,100.0,1.0,79.1,300.0,81.4,217.0,60.6,335.0,99.4,8.0,100.0,1.0,77.8,NaN,97.7,5,5.0,5,97.7,True,harvard university,6.0,Harvard University,United States of America,22680.0,10.1,0.27,"2 days, 5:47:00",97.0510,95.9,100.0,98.9,86.7,88.3,2026.0,6.0,53.0,"2 days, 5:47:00",harvard university,exact_name_country,100.0,True,Harvard University,Harvard University,harvard university,harvard university

In [13]:
print("Duplicate QS universities:",
      final_df["qs_Institution Name"].duplicated().sum())

print("Duplicate THE universities:",
      final_df["the_Name"].duplicated().sum())

print("Duplicate complete rows:",
      final_df.duplicated().sum())

Duplicate QS universities: 0
Duplicate THE universities: 0
Duplicate complete rows: 0

In [14]:
country_mismatch = (
    final_df["qs_Country/Territory"].astype(str)
    != final_df["the_Country"].astype(str)
)

print("Country mismatches:", country_mismatch.sum())

Country mismatches: 0

In [15]:
core_fields = [
    "qs_Institution Name",
    "qs_Country/Territory",
    "qs_2026_rank",
    "qs_AR SCORE",
    "qs_ER SCORE",
    "qs_FSR SCORE",
    "qs_CPF SCORE",
    "qs_IFR SCORE",
    "qs_ISR SCORE",
    "qs_ISD SCORE",
    "qs_IRN SCORE",
    "qs_EO SCORE",
    "the_Name",
    "the_Country",
    "the_rank",
    "the_Student Population",
    "the_Students to Staff Ratio",
    "the_Overall Score",
    "the_Teaching",
    "the_Research Environment",
    "the_Research Quality",
    "the_Industry Impact",
    "the_International Outlook",
    "the_female_to_male_ratio_clean",
]

# Keep only fields that exist
core_fields = [
    col for col in core_fields
    if col in final_df.columns
]

total_cells = len(final_df) * len(core_fields)
missing_cells = final_df[core_fields].isna().sum().sum()

missing_percentage = (
    missing_cells / total_cells
) * 100

completeness = 100 - missing_percentage

print("CORE COMPLETENESS CHECK")
print("=" * 60)
print("Rows:", len(final_df))
print("Core fields:", len(core_fields))
print("Total core cells:", total_cells)
print("Missing core cells:", missing_cells)
print(f"Missing percentage: {missing_percentage:.2f}%")
print(f"Completeness: {completeness:.2f}%")

print("\nRequirement:")
print("Completeness > 95%")
print("Missing values < 2%")

if completeness > 95 and missing_percentage < 2:
    print("\nPASS")
else:
    print("\nFAIL")

CORE COMPLETENESS CHECK
============================================================
Rows: 1008
Core fields: 24
Total core cells: 24192
Missing core cells: 142
Missing percentage: 0.59%
Completeness: 99.41%

Requirement:
Completeness > 95%
Missing values < 2%

PASS

In [16]:
missing_by_field = (
    final_df[core_fields]
    .isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    missing_by_field.to_frame("Missing Values")
)

                                Missing Values
the_female_to_male_ratio_clean              63
qs_IFR SCORE                                41
qs_ISR SCORE                                19
qs_ISD SCORE                                19
qs_AR SCORE                                  0
qs_Institution Name                          0
qs_2026_rank                                 0
qs_Country/Territory                         0
qs_CPF SCORE                                 0
qs_FSR SCORE                                 0
qs_ER SCORE                                  0
qs_IRN SCORE                                 0
the_Name                                     0
the_Country                                  0
the_rank                                     0
qs_EO SCORE                                  0
the_Student Population                       0
the_Students to Staff Ratio                  0
the_Teaching                                 0
the_Overall Score                            0
the_Research Environment                     0
the_Research Quality                         0
the_Industry Impact                          0
the_International Outlook                    0

In [17]:
print("MATCH TYPE SUMMARY")
display(final_df["match_type"].value_counts())

print("\nMATCH SIMILARITY")
display(final_df["match_similarity"].describe())

MATCH TYPE SUMMARY

match_type
exact_name_country        857
fuzzy_high                 83
manual_review_approved     68
Name: count, dtype: int64

MATCH SIMILARITY

count    1008.000000
mean       98.985149
std         2.766254
min        88.000000
25%       100.000000
50%       100.000000
75%       100.000000
max       100.000000
Name: match_similarity, dtype: float64

In [18]:
checks = {
    "Rows > 0": len(final_df) > 0,
    "Duplicate QS universities": final_df["qs_Institution Name"].duplicated().sum() == 0,
    "Duplicate THE universities": final_df["the_Name"].duplicated().sum() == 0,
    "Country mismatches": country_mismatch.sum() == 0,
    "Missing QS names": final_df["qs_Institution Name"].isna().sum() == 0,
    "Missing THE names": final_df["the_Name"].isna().sum() == 0,
    "Completeness > 95%": completeness > 95,
    "Missing values < 2%": missing_percentage < 2,
}

display(
    pd.DataFrame(
        {"Check": checks.keys(), "Passed": checks.values()}
    )
)

if all(checks.values()):
    print("\nFINAL STATUS: PASS")
    print("Dataset is ready for Tableau/dashboard development.")
else:
    print("\nFINAL STATUS: REVIEW REQUIRED")

                        Check  Passed
0                    Rows > 0    True
1   Duplicate QS universities    True
2  Duplicate THE universities    True
3          Country mismatches    True
4            Missing QS names    True
5           Missing THE names    True
6          Completeness > 95%    True
7         Missing values < 2%    True

FINAL STATUS: PASS
Dataset is ready for Tableau/dashboard development.

In [19]:
TABLEAU_FILE = OUTPUT_DIR / "university_cleaned_merged_data.csv"

print("Tableau-ready dataset:")
print(TABLEAU_FILE)

print("\nFinal shape:", final_df.shape)

Tableau-ready dataset:
C:\Users\Asus\infosys internshi\output\university_cleaned_merged_data.csv

Final shape: (1008, 61)

# Conclusion

The QS World University Rankings 2026 and Times Higher Education World University Rankings 2026 datasets were successfully cleaned, standardized, integrated, and validated.

### Final Results

- **Final integrated universities:** 1,008
- **Duplicate QS universities:** 0
- **Duplicate THE universities:** 0
- **Country mismatches:** 0
- **Core completeness:** 99.43%
- **Core missing values:** 0.57%
- **Required completeness:** >95%
- **Required missing values:** <2%

### Milestone 1 Status

**PASS — Data Collection and Preparation completed successfully.**

The resulting `university_cleaned_merged_data.csv` is ready for Tableau/dashboard development.