In [2]:
# University Ranking Data Cleaning and Integration

## Milestone 1 — Data Collection and Cleaning

# This notebook documents the preparation of the QS World University Rankings 2026 and Times Higher Education (THE) World University Rankings 2026 datasets.

### Objectives

# - Load and inspect both ranking datasets.
# - Check duplicates and missing values.
# - Standardize country names.
# - Normalize university names for cross-dataset matching.
# - Integrate QS and THE using an inner join.
# - Create a standardized Tableau-ready dataset.
# - Validate the final dataset.
# - Export the cleaned dataset for dashboard development.

In [3]:
import pandas as pd
import re
from pathlib import Path

In [4]:
# Project directory
PROJECT_DIR = Path.cwd().parent

# Data and output directories
DATA_DIR = PROJECT_DIR / "data"
OUTPUT_DIR = PROJECT_DIR / "output"

OUTPUT_DIR.mkdir(exist_ok=True)

print("Project directory:", PROJECT_DIR)
print("Data directory:", DATA_DIR)
print("Output directory:", OUTPUT_DIR)

Project directory: C:\Users\hp\OneDrive\Documents\Infosys Internship\Excel Datasets of 2026 Ranking
Data directory: C:\Users\hp\OneDrive\Documents\Infosys Internship\Excel Datasets of 2026 Ranking\data
Output directory: C:\Users\hp\OneDrive\Documents\Infosys Internship\Excel Datasets of 2026 Ranking\output

In [5]:
qs_file = DATA_DIR / "2026 QS World University Rankings.csv"

qs = pd.read_csv(qs_file)

print("QS dataset loaded successfully")
print("Rows:", len(qs))
print("Columns:", len(qs.columns))

QS dataset loaded successfully
Rows: 1501
Columns: 30

In [6]:
the_file = DATA_DIR / "THE World University Rankings 2026.xlsx"

the = pd.read_excel(the_file)

print("THE dataset loaded successfully")
print("Rows:", len(the))
print("Columns:", len(the.columns))

THE dataset loaded successfully
Rows: 2191
Columns: 14

In [7]:
print("QS DATASET")
print("-" * 50)
print(qs.info())

print("\nTHE DATASET")
print("-" * 50)
print(the.info())

QS DATASET
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 1501 entries, 0 to 1500
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   2026 Rank          1501 non-null   str
 1   Previous Rank      1389 non-null   str
 2   Institution Name   1501 non-null   str
 3   Country/Territory  1501 non-null   str
 4   Region             1501 non-null   str
 5   Size               1500 non-null   str
 6   Focus              1501 non-null   str
 7   Research           1500 non-null   str
 8   Status             1454 non-null   str
 9   AR SCORE           1501 non-null   float64
 10  AR RANK            1501 non-null   str
 11  ER SCORE           1501 non-null   float64
 12  ER RANK            1501 non-null   str
 13  FSR SCORE          1501 non-null   float64
 14  FSR RANK           1501 non-null   str
 15  CPF SCORE          1501 non-null   float64
 16  CPF RANK           1501 non-null   str
 17  IFR SCORE          1414 non-null   float64
 18  IFR RANK           1414 non-null   str
 19  ISR SCORE          1464 non-null   float64
 20  ISR RANK           1464 non-null   str
 21  ISD SCORE          1464 non-null   float64
 22  ISD RANK           1464 non-null   str
 23  IRN SCORE          1499 non-null   float64
 24  IRN RANK           1499 non-null   str
 25  EO SCORE           1501 non-null   float64
 26  EO RANK            1501 non-null   str
 27  SUS SCORE          1477 non-null   float64
 28  SUS RANK           1477 non-null   str
 29  Overall SCORE      1501 non-null   str
dtypes: float64(10), str(20)
memory usage: 351.9 KB
None

THE DATASET
--------------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 2191 entries, 0 to 2190
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     2191 non-null   int64
 1   Name                     2191 non-null   str
 2   Country                  2191 non-null   str
 3   Student Population       2191 non-null   int64
 4   Students to Staff Ratio  2191 non-null   float64
 5   International Students   2189 non-null   float64
 6   Female to Male Ratio     2103 non-null   object
 7   Overall Score            2191 non-null   float64
 8   Teaching                 2191 non-null   float64
 9   Research Environment     2191 non-null   float64
 10  Research Quality         2191 non-null   float64
 11  Industry Impact          2191 non-null   float64
 12  International Outlook    2191 non-null   float64
 13  Year                     2191 non-null   int64
dtypes: float64(8), int64(3), object(1), str(2)
memory usage: 239.8+ KB
None

In [8]:
print("QS SAMPLE")
display(qs.head())

print("\nTHE SAMPLE")
display(the.head())

QS SAMPLE

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7

THE SAMPLE

,Rank,Name,Country,Student Population,Students to Staff Ratio,International Students,Female to Male Ratio,Overall Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Year
0,1,University of Oxford,United Kingdom,22005,10.4,0.43,"2 days, 4:48:00",98.2100,97.2,100.0,97.7,99.9,96.4,2026
1,2,Massachusetts Institute of Technology,United States,11703,7.7,0.33,"1 day, 19:57:00",97.6735,99.2,95.3,99.6,100.0,91.9,2026
2,3,Princeton University,United States,8739,8.2,0.23,"1 day, 23:53:00",97.2110,98.2,97.3,99.0,98.0,85.4,2026
3,4,University of Cambridge,United Kingdom,21045,11.3,0.38,"2 days, 2:50:00",97.2065,96.2,99.9,97.1,87.6,96.3,2026
4,5,Stanford University,United States,17422,5.9,0.25,"2 days, 0:52:00",97.1510,97.5,97.4,99.5,100.0,83.9,2026

In [9]:
qs_duplicates = qs.duplicated().sum()
the_duplicates = the.duplicated().sum()

print("DUPLICATE CHECK")
print("-" * 50)
print("QS duplicate rows:", qs_duplicates)
print("THE duplicate rows:", the_duplicates)

DUPLICATE CHECK
--------------------------------------------------
QS duplicate rows: 0
THE duplicate rows: 0

In [10]:
print("MISSING VALUES — QS")
print("-" * 50)
display(qs.isna().sum().sort_values(ascending=False))

print("\nMISSING VALUES — THE")
print("-" * 50)
display(the.isna().sum().sort_values(ascending=False))

MISSING VALUES — QS
--------------------------------------------------

Previous Rank        112
IFR SCORE             87
IFR RANK              87
Status                47
ISR RANK              37
ISR SCORE             37
ISD RANK              37
ISD SCORE             37
SUS RANK              24
SUS SCORE             24
IRN SCORE              2
IRN RANK               2
Research               1
Size                   1
FSR SCORE              0
ER RANK                0
ER SCORE               0
AR RANK                0
AR SCORE               0
Focus                  0
Country/Territory      0
Region                 0
Institution Name       0
2026 Rank              0
CPF RANK               0
FSR RANK               0
CPF SCORE              0
EO SCORE               0
EO RANK                0
Overall SCORE          0
dtype: int64

MISSING VALUES — THE
--------------------------------------------------

Female to Male Ratio       88
International Students      2
Name                        0
Country                     0
Student Population          0
Rank                        0
Students to Staff Ratio     0
Overall Score               0
Teaching                    0
Research Environment        0
Research Quality            0
Industry Impact             0
International Outlook       0
Year                        0
dtype: int64

In [11]:
## Initial Data Quality Assessment

# Both source datasets were inspected for structure, duplicate records, and missing values.

# - QS contains 1,501 university records and 30 columns.
# - THE contains 2,191 university records and 14 columns.
# - No duplicate rows were identified in either source dataset.
# - Missing values are present in some ranking indicators and institutional attributes.
# - Missing values are retained where they represent unavailable source data rather than being replaced with artificial zero values.

In [12]:
# Country-name standardization mapping

country_mapping = {
    "China (Mainland)": "China",
    "Hong Kong SAR, China": "Hong Kong",
    "Iran (Islamic Republic of)": "Iran",
    "Macao SAR, China": "Macao",
    "Republic of Korea": "South Korea",
    "Syrian Arab Republic": "Syria",
    "Türkiye": "Turkey",
    "United States of America": "United States",
    "Venezuela (Bolivarian Republic of)": "Venezuela",
    "Viet Nam": "Vietnam"
}

In [13]:
qs["Standard Country"] = (
    qs["Country/Territory"]
    .replace(country_mapping)
)

the["Standard Country"] = (
    the["Country"]
    .replace(country_mapping)
)

print("Country standardization completed.")

Country standardization completed.

In [14]:
qs_countries = set(qs["Standard Country"].dropna().unique())
the_countries = set(the["Standard Country"].dropna().unique())

common_countries = qs_countries & the_countries

print("STANDARDIZED COUNTRY CHECK")
print("-" * 50)

print("QS unique countries:", len(qs_countries))
print("THE unique countries:", len(the_countries))
print("Common standardized countries:", len(common_countries))

print("\nQS-only countries:")
print(sorted(qs_countries - the_countries))

print("\nTHE-only countries:")
print(sorted(the_countries - qs_countries))

STANDARDIZED COUNTRY CHECK
--------------------------------------------------
QS unique countries: 106
THE unique countries: 115
Common standardized countries: 97

QS-only countries:
['Dominican Republic', 'Ethiopia', 'Guatemala', 'Honduras', 'Kyrgyzstan', 'Panama', 'Puerto Rico', 'Sudan', 'Uruguay']

THE-only countries:
['Algeria', 'Botswana', 'Fiji', 'Jamaica', 'Kosovo', 'Mauritius', 'Mongolia', 'Montenegro', 'Mozambique', 'Namibia', 'Nepal', 'North Macedonia', 'Rwanda', 'Senegal', 'Tanzania', 'Yemen', 'Zambia', 'Zimbabwe']

In [16]:
## Country Standardization

# The QS and THE datasets use different naming conventions for several countries and territories.

# Examples include:

# - `United States of America` → `United States`
# - `China (Mainland)` → `China`
# - `Republic of Korea` → `South Korea`
# - `Türkiye` → `Turkey`
# - `Viet Nam` → `Vietnam`
# - `Iran (Islamic Republic of)` → `Iran`
# - `Syrian Arab Republic` → `Syria`
# - `Hong Kong SAR, China` → `Hong Kong`
# - `Macao SAR, China` → `Macao`

# A standardized country field was created while preserving the original source fields.

# Countries present in only one source were not artificially added to the other dataset or removed at this stage.

In [17]:
def normalize_university_name(name):
    """
    Create a standardized matching key for university names.
    The original source names remain unchanged.
    """

    if pd.isna(name):
        return ""

    name = str(name).strip().lower()

    # Remove text inside parentheses
    name = re.sub(r"\([^)]*\)", "", name)

    # Remove leading "the"
    name = re.sub(r"^the\s+", "", name)

    # Standardize ampersand
    name = name.replace("&", "and")

    # Remove punctuation
    name = re.sub(r"[^\w\s]", " ", name)

    # Normalize multiple spaces
    name = re.sub(r"\s+", " ", name).strip()

    return name

In [18]:
qs["University Match Name"] = (
    qs["Institution Name"]
    .apply(normalize_university_name)
)

the["University Match Name"] = (
    the["Name"]
    .apply(normalize_university_name)
)

print("University name normalization completed.")

University name normalization completed.

In [19]:
print("QS UNIVERSITY NAME NORMALIZATION")
print("-" * 80)

display(
    qs[
        ["Institution Name", "University Match Name"]
    ].head(20)
)

print("\nTHE UNIVERSITY NAME NORMALIZATION")
print("-" * 80)

display(
    the[
        ["Name", "University Match Name"]
    ].head(20)
)

QS UNIVERSITY NAME NORMALIZATION
--------------------------------------------------------------------------------

,Institution Name,University Match Name
0,Massachusetts Institute of Technology (MIT),massachusetts institute of technology
1,Imperial College London,imperial college london
2,Stanford University,stanford university
3,University of Oxford,university of oxford
4,Harvard University,harvard university
5,University of Cambridge,university of cambridge
6,ETH Zurich (Swiss Federal Institute of Technol...,eth zurich
7,National University of Singapore (NUS),national university of singapore
8,UCL (University College London),ucl
9,California Institute of Technology (Caltech),california institute of technology
10,The University of Hong Kong,university of hong kong
11,"Nanyang Technological University, Singapore (N...",nanyang technological university singapore
12,University of Chicago,university of chicago
13,Peking University,peking university
14,University of Pennsylvania,university of pennsylvania
15,Cornell University,cornell university
16,Tsinghua University,tsinghua university
17,"University of California, Berkeley (UCB)",university of california berkeley
18,The University of Melbourne,university of melbourne
19,The University of New South Wales,university of new south wales

THE UNIVERSITY NAME NORMALIZATION
--------------------------------------------------------------------------------

,Name,University Match Name
0,University of Oxford,university of oxford
1,Massachusetts Institute of Technology,massachusetts institute of technology
2,Princeton University,princeton university
3,University of Cambridge,university of cambridge
4,Stanford University,stanford university
5,Harvard University,harvard university
6,California Institute of Technology,california institute of technology
7,Imperial College London,imperial college london
8,"University of California, Berkeley",university of california berkeley
9,Yale University,yale university
10,ETH Zurich,eth zurich
11,Tsinghua University,tsinghua university
12,Peking University,peking university
13,University of Pennsylvania,university of pennsylvania
14,The University of Chicago,university of chicago
15,Johns Hopkins University,johns hopkins university
16,National University of Singapore,national university of singapore
17,"University of California, Los Angeles",university of california los angeles
18,Cornell University,cornell university
19,Columbia University,columbia university

In [20]:
qs_names = set(qs["University Match Name"])
the_names = set(the["University Match Name"])

common_names = qs_names & the_names

print("UNIVERSITY NAME MATCHING")
print("-" * 50)

print("QS universities:", len(qs_names))
print("THE universities:", len(the_names))
print("Normalized exact matches:", len(common_names))

print(
    "QS match percentage:",
    round(len(common_names) / len(qs_names) * 100, 2),
    "%"
)

print(
    "THE match percentage:",
    round(len(common_names) / len(the_names) * 100, 2),
    "%"
)

UNIVERSITY NAME MATCHING
--------------------------------------------------
QS universities: 1501
THE universities: 2191
Normalized exact matches: 870
QS match percentage: 57.96 %
THE match percentage: 39.71 %

In [21]:
matched_data = pd.merge(
    qs,
    the,
    on=["University Match Name", "Standard Country"],
    how="inner",
    suffixes=("_QS", "_THE")
)

print("INNER JOIN RESULTS")
print("-" * 50)

print("QS universities:", len(qs))
print("THE universities:", len(the))
print("Matched universities:", len(matched_data))

print(
    "QS matched:",
    round(len(matched_data) / len(qs) * 100, 2),
    "%"
)

print(
    "THE matched:",
    round(len(matched_data) / len(the) * 100, 2),
    "%"
)

INNER JOIN RESULTS
--------------------------------------------------
QS universities: 1501
THE universities: 2191
Matched universities: 870
QS matched: 57.96 %
THE matched: 39.71 %

In [22]:
## University Matching and Dataset Integration

# University names were normalized to create a matching key while preserving the original institution names.

# The normalization process:

# 1. Converts names to lowercase.
# 2. Removes text contained in parentheses.
# 3. Removes a leading `The`.
# 4. Standardizes ampersands.
# 5. Removes punctuation.
# 6. Normalizes whitespace.

# QS and THE records were then integrated using an **inner join** on:

# - `University Match Name`
# - `Standard Country`

# Only universities that could be matched across both datasets were retained for the comparative analysis dataset.

# The resulting dataset contains 870 matched universities.

In [23]:
# --------------------------------------------------
# Create final Tableau-ready dataset
# --------------------------------------------------

final_data = pd.DataFrame({
    # University information
    "University Name": matched_data["Institution Name"],
    "Country": matched_data["Standard Country"],
    "Region": matched_data["Region"],

    # QS ranking information
    "QS Rank": matched_data["2026 Rank"],
    "QS Previous Rank": matched_data["Previous Rank"],
    "QS Overall Score": matched_data["Overall SCORE"],

    "QS Academic Reputation Score": matched_data["AR SCORE"],
    "QS Academic Reputation Rank": matched_data["AR RANK"],

    "QS Employer Reputation Score": matched_data["ER SCORE"],
    "QS Employer Reputation Rank": matched_data["ER RANK"],

    "QS Faculty Student Ratio Score": matched_data["FSR SCORE"],
    "QS Faculty Student Ratio Rank": matched_data["FSR RANK"],

    "QS Citations per Faculty Score": matched_data["CPF SCORE"],
    "QS Citations per Faculty Rank": matched_data["CPF RANK"],

    "QS International Faculty Ratio Score": matched_data["IFR SCORE"],
    "QS International Faculty Ratio Rank": matched_data["IFR RANK"],

    "QS International Student Ratio Score": matched_data["ISR SCORE"],
    "QS International Student Ratio Rank": matched_data["ISR RANK"],

    "QS International Student Diversity Score": matched_data["ISD SCORE"],
    "QS International Student Diversity Rank": matched_data["ISD RANK"],

    "QS International Research Network Score": matched_data["IRN SCORE"],
    "QS International Research Network Rank": matched_data["IRN RANK"],

    "QS Employment Outcomes Score": matched_data["EO SCORE"],
    "QS Employment Outcomes Rank": matched_data["EO RANK"],

    "QS Sustainability Score": matched_data["SUS SCORE"],
    "QS Sustainability Rank": matched_data["SUS RANK"],

    # THE ranking information
    "THE Rank": matched_data["Rank"],
    "THE Overall Score": matched_data["Overall Score"],

    "THE Student Population": matched_data["Student Population"],
    "THE Students to Staff Ratio": matched_data["Students to Staff Ratio"],
    "THE International Students": matched_data["International Students"],
    "THE Female to Male Ratio": matched_data["Female to Male Ratio"],

    "THE Teaching Score": matched_data["Teaching"],
    "THE Research Environment Score": matched_data["Research Environment"],
    "THE Research Quality Score": matched_data["Research Quality"],
    "THE Industry Impact Score": matched_data["Industry Impact"],
    "THE International Outlook Score": matched_data["International Outlook"],

    "Ranking Year": matched_data["Year"]
})

print("Tableau-ready dataset created.")
print("Rows:", len(final_data))
print("Columns:", len(final_data.columns))

Tableau-ready dataset created.
Rows: 870
Columns: 38

In [25]:
# --------------------------------------------------
# Remove duplicate university-country combinations
# --------------------------------------------------

duplicates_before = final_data.duplicated(
    subset=["University Name", "Country"]
).sum()

final_data = final_data.drop_duplicates(
    subset=["University Name", "Country"]
).reset_index(drop=True)

duplicates_after = final_data.duplicated(
    subset=["University Name", "Country"]
).sum()

print("Duplicate university-country records before:", duplicates_before)
print("Duplicate university-country records after:", duplicates_after)
print("Final rows:", len(final_data))

Duplicate university-country records before: 0
Duplicate university-country records after: 0
Final rows: 870

In [26]:
# --------------------------------------------------
# Sort final dataset by QS ranking
# --------------------------------------------------

final_data = final_data.sort_values(
    by="QS Rank",
    ascending=True
).reset_index(drop=True)

display(
    final_data[
        [
            "University Name",
            "Country",
            "QS Rank",
            "THE Rank",
            "QS Overall Score",
            "THE Overall Score"
        ]
    ].head(10)
)

,University Name,Country,QS Rank,THE Rank,QS Overall Score,THE Overall Score
0,Massachusetts Institute of Technology (MIT),United States,1,2,100,97.6735
1,California Institute of Technology (Caltech),United States,10,7,94.3,96.3165
2,University of Isfahan,Iran,1001-1200,1215,-,31.8805
3,University of Ioannina,Greece,1001-1200,1335,-,29.7630
4,University of Ibadan,Nigeria,1001-1200,942,-,36.4750
5,University of East London,United Kingdom,1001-1200,1076,-,34.0995
6,University of Deusto,Spain,1001-1200,1213,-,31.9165
7,University of Denver,United States,1001-1200,608,-,43.5470
8,University of Colombo,Sri Lanka,1001-1200,1008,-,35.3415
9,University of Anbar,Iraq,1001-1200,1298,-,30.4180

In [27]:
# --------------------------------------------------
# Final data-quality validation
# --------------------------------------------------

missing_values = final_data.isna().sum()

missing_values = (
    missing_values[missing_values > 0]
    .sort_values(ascending=False)
)

total_cells = (
    final_data.shape[0] *
    final_data.shape[1]
)

missing_cells = final_data.isna().sum().sum()

missing_percentage = (
    missing_cells / total_cells
) * 100

print("FINAL DATA QUALITY VALIDATION")
print("-" * 50)

print("Rows:", len(final_data))
print("Columns:", len(final_data.columns))
print("Duplicate rows:", final_data.duplicated().sum())

print("\nColumns containing missing values:")
display(missing_values)

print(
    "\nOverall missing-value percentage:",
    round(missing_percentage, 2),
    "%"
)

FINAL DATA QUALITY VALIDATION
--------------------------------------------------
Rows: 870
Columns: 38
Duplicate rows: 0

Columns containing missing values:

THE Female to Male Ratio                    52
QS Previous Rank                            42
QS International Faculty Ratio Score        39
QS International Faculty Ratio Rank         39
QS International Student Ratio Rank         15
QS International Student Ratio Score        15
QS International Student Diversity Score    15
QS International Student Diversity Rank     15
QS Sustainability Score                      2
QS Sustainability Rank                       2
dtype: int64

Overall missing-value percentage: 0.71 %

In [28]:
print("FINAL DATASET COLUMNS")
print("-" * 50)

for number, column in enumerate(final_data.columns, start=1):
    print(f"{number}. {column}")

FINAL DATASET COLUMNS
--------------------------------------------------
1. University Name
2. Country
3. Region
4. QS Rank
5. QS Previous Rank
6. QS Overall Score
7. QS Academic Reputation Score
8. QS Academic Reputation Rank
9. QS Employer Reputation Score
10. QS Employer Reputation Rank
11. QS Faculty Student Ratio Score
12. QS Faculty Student Ratio Rank
13. QS Citations per Faculty Score
14. QS Citations per Faculty Rank
15. QS International Faculty Ratio Score
16. QS International Faculty Ratio Rank
17. QS International Student Ratio Score
18. QS International Student Ratio Rank
19. QS International Student Diversity Score
20. QS International Student Diversity Rank
21. QS International Research Network Score
22. QS International Research Network Rank
23. QS Employment Outcomes Score
24. QS Employment Outcomes Rank
25. QS Sustainability Score
26. QS Sustainability Rank
27. THE Rank
28. THE Overall Score
29. THE Student Population
30. THE Students to Staff Ratio
31. THE International Students
32. THE Female to Male Ratio
33. THE Teaching Score
34. THE Research Environment Score
35. THE Research Quality Score
36. THE Industry Impact Score
37. THE International Outlook Score
38. Ranking Year

In [30]:
# --------------------------------------------------
# Export final cleaned dataset
# --------------------------------------------------

cleaned_file = OUTPUT_DIR / "university_cleaned.csv"

final_data.to_csv(
    cleaned_file,
    index=False
)

print("Cleaned dataset exported successfully.")
print("File:", cleaned_file)

Cleaned dataset exported successfully.
File: C:\Users\hp\OneDrive\Documents\Infosys Internship\Excel Datasets of 2026 Ranking\output\university_cleaned.csv

In [31]:
display(final_data.head(10))

,University Name,Country,Region,QS Rank,QS Previous Rank,QS Overall Score,QS Academic Reputation Score,QS Academic Reputation Rank,QS Employer Reputation Score,QS Employer Reputation Rank,...,THE Student Population,THE Students to Staff Ratio,THE International Students,THE Female to Male Ratio,THE Teaching Score,THE Research Environment Score,THE Research Quality Score,THE Industry Impact Score,THE International Outlook Score,Ranking Year
0,Massachusetts Institute of Technology (MIT),United States,Americas,1,1,100,100.0,4,100.0,2,...,11703,7.7,0.33,"1 day, 19:57:00",99.2,95.3,99.6,100.0,91.9,2026
1,California Institute of Technology (Caltech),United States,Americas,10,10,94.3,98.3,33,99.2,23,...,2401,6.7,0.33,39 : 61,96.4,97.4,96.8,100.0,87.9,2026
2,University of Isfahan,Iran,Asia,1001-1200,NaN,-,7.7,701+,10.7,701+,...,17094,22.6,0.05,"2 days, 10:42:00",29.0,18.3,46.8,38.9,32.3,2026
3,University of Ioannina,Greece,Europe,1001-1200,1001-1200,-,9.4,701+,5.6,701+,...,33322,38.1,0.03,"2 days, 6:46:00",16.9,15.7,50.5,52.8,39.5,2026
4,University of Ibadan,Nigeria,Africa,1001-1200,1001-1200,-,11.6,701+,16.6,701+,...,36851,17.6,0.00,"2 days, 2:50:00",29.6,15.6,63.5,22.1,43.8,2026
5,University of East London,United Kingdom,Europe,1001-1200,901-950,-,3.9,701+,6.5,701+,...,18135,28.6,0.57,"2 days, 1:51:00",23.6,15.3,49.5,32.2,87.5,2026
6,University of Deusto,Spain,Europe,1001-1200,1001-1200,-,8.9,701+,29.8,477,...,10138,18.7,0.11,"2 days, 8:44:00",20.7,20.6,49.3,39.9,46.0,2026
7,University of Denver,United States,Americas,1001-1200,951-1000,-,7.8,701+,12.2,701+,...,10234,13.3,0.05,"2 days, 14:38:00",40.2,25.5,63.5,57.2,39.4,2026
8,University of Colombo,Sri Lanka,Asia,1001-1200,951-1000,-,15.1,701+,20.9,626,...,35859,32.1,0.01,"2 days, 13:39:00",26.0,11.7,67.1,27.4,40.7,2026
9,University of Anbar,Iraq,Asia,1001-1200,NaN,-,25.3,507,15.4,701+,...,27797,11.1,0.01,"2 days, 9:43:00",25.0,11.1,53.2,36.6,32.0,2026

In [33]:
## Final Data Quality Summary

# The final integrated dataset contains **870 universities** that were successfully matched between the QS World University Rankings 2026 and the Times Higher Education (THE) World University Rankings 2026 datasets.

# ### Final dataset characteristics

# - **Rows:** 870
# - **Columns:** 38
# - **Duplicate rows:** 0
# - **Overall missing-value percentage:** 0.71%

# The final dataset contains standardized university and country fields together with QS and THE ranking indicators.

# Missing values were retained where the original source datasets did not provide a value. They were not replaced with zero because zero would represent an actual numerical value rather than unavailable information.

# The cleaned dataset was exported as:

# `output/university_cleaned.csv`

# This dataset is intended for subsequent Tableau dashboard development and comparative analysis.

In [34]:
# Final export verification

check = pd.read_csv(cleaned_file)

print("EXPORTED FILE VERIFICATION")
print("-" * 50)
print("Rows:", len(check))
print("Columns:", len(check.columns))
print("Duplicate rows:", check.duplicated().sum())
print("Missing values:", round(
    check.isna().sum().sum() /
    (check.shape[0] * check.shape[1]) * 100,
    2
), "%")

EXPORTED FILE VERIFICATION
--------------------------------------------------
Rows: 870
Columns: 38
Duplicate rows: 0
Missing values: 0.71 %